### ISSUE TITLE
Feature: Radio Channel Management with qb-radio

### ISSUE THREAD

**Issue by burnoutprojects** [Swift-peak-hosting-dev/Swift-Development-Integrations-v3#5]
# Current Status:  🚧 WIP

## Description
Currently I rewrote the [qb-radio](https://github.com/qbcore-framework/qb-radio) script to implement some core missing functions for communication with SnailyCAD API. After the development process and release of the new modified version of the script, you have to remove the original `qb-radio` script and add our script if you want to use with SnailyCAD instance.

## TODO

- [ ] Rewrote the [qb-radio](https://github.com/qbcore-framework/qb-radio) 
  - [ ] Add SnailyCAD integration
  - [ ] Fix some small UI bugs
